### ISSUE TITLE
[FEATURE] Code Cleanup

### ISSUE THREAD

**Issue by DebadityaPal** [DebadityaPal/PlagiarismChecker#3]
Currently, it has been brought to our notice that certain functions aren't being used in the execution of the product. These functions are totally isolated and hence removing them should not break anything.
The contributor should ideally follow the chain of function calls and determine these stray functions and remove them from the codebase. The result would be a cleaner and concise codebase.

**Comment by eldbud** [comment]
i'll try and give it a go :)

**Comment by gaurav879** [comment]
@DebadityaPal I would like to work on this.

**Comment by DebadityaPal** [comment]
Sure @gaurav879 go ahead!

**Comment by gaurav879** [comment]
@Debaditya-Pal 
I forked the project and I tried to run it.
Its showing "OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen importlib._bootstrap>' " this error.

**Comment by DebadityaPal** [comment]
@gaurav879 can you send me the entire traceback? that would help me debug the issue.

**Comment by gaurav879** [comment]
@Debaditya-Pal 
PS C:\Users\gaura\OneDrive\Desktop\plag\backend> python manage.py runserver 8000
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\apps\config.py", line 224, in create
    import_module(entry)
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rest_framework'
Traceback (most recent call last):
  File "C:\Users\gaura\OneDrive\Desktop\plag\backend\manage.py", line 22, in <module>
    main()
  File "C:\Users\gaura\OneDrive\Desktop\plag\backend\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 96, in handle
    self.run(**options)
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 103, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 638, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 623, in start_django
    reloader.run(django_main_thread)
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 329, in run
    self.run_loop()
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 335, in run_loop
    next(ticker)
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 375, in tick
    for filepath, mtime in self.snapshot_files():
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 391, in snapshot_files
    for file in self.watched_files():
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 289, in watched_files
    yield from iter_all_python_module_files()
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 116, in iter_all_python_module_files
    return iter_modules_and_files(modules, frozenset(_error_files))
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 152, in iter_modules_and_files
    if not path.exists():
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1407, in exists
    self.stat()
  File "C:\Users\gaura\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1221, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen importlib._bootstrap>'
PS C:\Users\gaura\OneDrive\Desktop\plag\backend>

**Comment by DebadityaPal** [comment]
Have you activated the virtual environment and installed the dependencies?>

**Comment by gaurav879** [comment]
Yes sir. @DebadityaPal

**Comment by DebadityaPal** [comment]
Try doing a fresh install, since others arent facing this issue, a fresh installation should fix this.

**Comment by gaurav879** [comment]
@DebadityaPal 
Sir I tried installing freshly in virtual environment again.
There is some issue in numpy installation.

**Comment by DebadityaPal** [comment]
Tagging @hs2361, @kc611 You guys got any idea?

**Comment by kc611** [comment]
The error seems to be a ModuleNotFound error for Django's REST Framework. 

@gaurav879 can you confirm if you have that installed. 

You could simply do a 
```
pip install djangorestframework
```
To check if it's installed globally and also check Django's settings.py file to see if you added `rest_framework` within the Installed_apps list.

**Comment by gaurav879** [comment]
Yes sir it worked now.

**Comment by gaurav879** [comment]
Sir @DebadityaPal I found 2 functions trainBatch (self, batch)in models.py and inference(filepath) in prediction.py should I simply remove them or comment them ?

**Comment by DebadityaPal** [comment]
@gaurav879 comment them out for now.

**Comment by gaurav879** [comment]
@DebadityaPal Sir I have opened PR #9 that fixes this issue.
